### ISSUE TITLE
Encode vs encode packed

### ISSUE THREAD

**Issue by osarrouy** [openethereum/ethabi#179]
Hi all,

I was wondering if there was any easy way to build an `encodePacked` bytes array from an array of `Token` through `ethabi`. I've tried to search through the doc but didn't fin anything beyond the regular `encode` function which seems _not to_ pack the args.

Thanks.

**Comment by algorithmicbtc** [comment]
Hi @osarrouy, did you find a solution of this?

**Comment by ppoliani** [comment]
any updates on this?

**Comment by nlordell** [comment]
AFAIK, there is no support for packed encoding in this crate.
